<?php

/**
 * @file
 * Install, update and uninstall functions for the Rick and Morty module.
 */
/**
 * Implements hook_update_N().
 */
function rick_and_morty_module_update_8001() {
  // Load and import the configuration.
  \Drupal::configFactory()->getEditable('node.type.character')->save();
  \Drupal::configFactory()->getEditable('node.type.location')->save();
  \Drupal::configFactory()->getEditable('node.type.episode')->save();
}
